### ISSUE TITLE
 undefined.NRMModularAgentPackage;

### ISSUE THREAD

**Issue by mahesh970098** [newrelic/newrelic-react-native-agent#124]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

node_modules\newrelic-react-native-agent\android\src\main\java\com\NewRelic\NRMModularAgentModule.java:431: warning: [unchecked] unchecked cast        
        Map<String, Object> stackFramesMap = (Map<String, Object>) exceptionMap.get("stackFrames");
                                                                                   ^
  required: Map<String,Object>
  found:    Object
project\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:43: error: package undefined does not exist
import undefined.NRMModularAgentPackage;
                ^
D:\project\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:175: error: cannot find symbol
      new NRMModularAgentPackage(),
          ^
  symbol:   class NRMModularAgentPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, metro or simulator/device logs, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Output of `npx react-native info`
* ex: Which platform is the issue happening on? (Android, iOS, tvOS, etc.)
* ex: Any conflicting packages installed?

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

ex: If appropriate and possible, it would be helpful to add [Charles traces](https://forum.newrelic.com/s/hubtopic/aAX8W0000008bQlWAI/relic-solution-setting-up-and-collecting-charles-trace-for-android-apps).

**Comment by ndesai-newrelic** [comment]
@mahesh970098 can you check this ?  https://github.com/newrelic/newrelic-react-native-agent/issues/118

**Comment by mahesh970098** [comment]
@ndesai-newrelic 
 I've been troubleshooting an issue that's not related to an iOS pods. I followed the steps outlined in the README file, but I've hit a roadblock. When I run the code using the command (`npx react-native run-android`), I encounter an error message: 

"import undefined.NRMModularAgentPackage; on PackageList.java:43: error: package undefined in android folder."

I'd appreciate any guidance or insights on how to resolve this problem. I followed the steps carefully, but it seems there's an issue with package imports that I'm not sure how to address. Your assistance in resolving this matter would be highly valuable. Thank you in advance.

**Comment by ndesai-newrelic** [comment]
@ndesai-newrelic which version of react native are you using?

**Comment by ahsan-lebara** [comment]
I am facing same issue.

**Comment by oguzydz** [comment]
My react native version is 0.70.5, I made the appending package name to `AndroidManifest.xml`. Do we handle this issue for 0.70.x versions? I'll be blocked with this issue for now. Thanks!

**Comment by ahsan-lebara** [comment]
``I have added the package name, but still, the app is not compilable. 

Manifest file:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.newrelic">
</manifest>`

Error:

```
/Volumes/Data/Lebara/storybook-mobile-newRelic/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:43: error: cannot find symbol
import com.newrelic.NRMModularAgentPackage;
                   ^
  symbol:   class NRMModularAgentPackage
  location: package com.newrelic
/Volumes/Data/Lebara/storybook-mobile-newRelic/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:145: error: cannot find symbol
      new NRMModularAgentPackage(),
          ^
  symbol:   class NRMModularAgentPackage
  location: class PackageList
Note: /Volumes/Data/Lebara/storybook-mobile-newRelic/android/app/src/debug/java/com/storybookmobile/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProductionDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by ndesai-newrelic** [comment]
it should be <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="**com.Newrelic**"> </manifest>

**Comment by ahsan-lebara** [comment]
Tried it, still not compilable.

```
Task :app:compileProductionDebugJavaWithJavac FAILED
/Volumes/Data/storybook-mobile-newRelic/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:43: error: package com.Newrelic does not exist
import com.Newrelic.NRMModularAgentPackage;
                   ^
/Volumes/Data/storybook-mobile-newRelic/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:145: error: cannot find symbol
      new NRMModularAgentPackage(),
          ^
  symbol:   class NRMModularAgentPackage
  location: class PackageList
Note: /Volumes/Data/storybook-mobile-newRelic/android/app/src/debug/java/com/storybookmobile/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by ndesai-newrelic** [comment]
@ahsan-lebara I successfully built the project using version 0.66.5. can you try it one more time?

**Comment by ol1000** [comment]
@ndesai-newrelic Hi there I can confirm they have tried this one more time and get them same issue. Would it be possible for you get get on a screen share with the customer and work to a solution?

**Comment by ol1000** [comment]
Sorry for any confusion. I am ohunt@newrelic.com the SC for Lebara account

**Comment by ol1000** [comment]
Reaching out to customer to get available times

**Comment by ol1000** [comment]
Customer available 11:00 BST 13th September. Oisin Buckley to arrange IE based support for tomorrow

**Comment by ndesai-newrelic** [comment]
@ahsan-lebara @mahesh970098 @oguzydz the issue is fixed, can you check from your side?

**Comment by faizantariq1** [comment]
while running on android with latest version 1.3.3. still facing the same issue.

/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:8: error: package android.util does not exist

**Comment by ndesai-newrelic** [comment]
@faizantariq1 i will check this issue from our side.

**Comment by ndesai-newrelic** [comment]
@faizantariq1 i am seeing the android.util package on this line.https://github.com/newrelic/newrelic-react-native-agent/blob/f89dfdb80361adfeda1186148068f42ef4d2f302/android/src/main/java/com/NewRelic/NRMModularAgentModule.java#L8

**Comment by ahsan-lebara** [comment]
Can you explain it little more, how it should be fixed form frontend side? Issues looks from SDK.

**Comment by ndesai-newrelic** [comment]
@ahsan-lebara your errro is showing **package android.util does not exist** which is android sdk package, can you reinstall the package and try to build again?

**Comment by faizantariq2** [comment]
Hi @ndesai-newrelic . i just paste one error related to NRMModularAgentModule.java but actually we are receiving multiple error related to this module. you can see the error below. i have reinstall the package again but still seeing this issue.


newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:8: error: package android.util does not exist
import android.util.Log;
                   ^
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:49: error: cannot find symbol
            Log.w("NRMA", "calling start agent for RN bridge is deprecated. The agent automatically starts on creation.");
            ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:131: error: cannot access ContextWrapper
                        .start(reactContext);
                        ^
  class file for android.content.ContextWrapper not found
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:141: error: cannot access Context
                        .start(reactContext);
                        ^
  class file for android.content.Context not found
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:158: error: cannot find symbol
                    Log.w("NRMA", "TODO!! Skipping NULL attribute in react-native shim recordCustomEvent ");
                    ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:170: error: cannot find symbol
                    Log.w("NRMA", "TODO!! Skipping MAP attribute in react-native shim recordCustomEvent ");
                    ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:173: error: cannot find symbol
                    Log.w("NRMA", "TODO!! Skipping ARRAY attribute in react-native shim recordCustomEvent ");
                    ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:407: error: cannot find symbol
            Log.w("NRMA", e.getMessage());
            ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:419: error: cannot find symbol
            Log.w("NRMA", "Null dictionary given to recordHandledException");
            ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:428: error: cannot find symbol
            Log.w("NRMA", "No stack frames in recordHandledException");
            ^
  symbol:   variable Log
  location: class NRMModularAgentModule
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:431: warning: [unchecked] unchecked cast
        Map<String, Object> stackFramesMap = (Map<String, Object>) exceptionMap.get("stackFrames");
                                                                                   ^
  required: Map<String,Object>
  found:    Object
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:443: warning: [unchecked] unchecked cast
                Map<String, Object> element = (Map<String, Object>) stackFrameMap.get(Integer.toString(i));
                                                                                     ^
  required: Map<String,Object>
  found:    Object
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:445: error: package android.os.Build does not exist
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                                    ^
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:445: error: package android.os.Build does not exist
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                                                                        ^
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:453: error: package android.os.Build does not exist
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                                    ^
/node_modules/newrelic-react-native-agent/android/src/main/java/com/NewRelic/NRMModularAgentModule.java:453: error: package android.os.Build does not exist
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                                                                        ^

**Comment by ndesai-newrelic** [comment]
@mahesh970098 did you try it our latest release?

**Comment by faizantariq1** [comment]
Hi @ndesai-newrelic , when we disconnected the meeting, after that app is open still facing this issue.
TypeError: null is not an object (evaluating 'NRMModularAgent.startAgent')

**Comment by Garvnanwani** [comment]
@faizantariq1  were you able to find a solution for TypeError: null is not an object (evaluating 'NRMModularAgent.startAgent') this issue ?

**Comment by faizantariq1** [comment]
@Garvnanwani No, I used the ^1.2.1 version at that time.
